arch:
#- amd64
- arm64

services:
- docker

language: 
  minimal

before_install:
- ls -las
- pwd
- (cd agent && ../ci/01-build.sh)                                         
- (cd agent && ../ci/02-test.sh)                                         
- (cd agent && ../ci/03-publish-npm.sh)                                         

script:
- npm test
