arch:
- amd64
- arm64

language: minimal
services: docker

script:
- (cd agent && ../ci/01-build.sh)                                         
- (cd agent && ../ci/02-test.sh)                                         
- (cd agent && ../ci/03-publish-npm.sh)
- (cd agent && ../ci/04-publish-docker.sh)
- (cd webapp && ../ci/05-publish-static.sh)
