arch:
- amd64
- arm64

language: minimal
services: docker
install: sudo apt-get -y install jq sed curl

before_script:
- mkdir $HOME/.docker/
- echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
# - cat <<< $(jq '.+{"experimental":"enabled"}' ~/.docker/config.json) > ~/.docker/config.json

script:
- (cd agent && ../ci/01-build.sh)                                         
- (cd agent && ../ci/02-test.sh)                                         
- (cd agent && ../ci/03-publish-npm.sh)
- (cd agent && ../ci/04-publish-docker.sh)
