arch:
- amd64
- arm64

services:
- docker

language: 
  minimal

script:
- (cd agent && ../ci/01-build.sh)                                         
- (cd agent && ../ci/02-test.sh)                                         
- (cd agent && ../ci/03-publish-npm.sh)
