version: "3.7"
services:
  webapp:
    image: node:14.8
    volumes:
      - "./webapp:/mnt/webapp"
    working_dir: "/mnt/webapp"
    entrypoint: "/bin/bash -c"
    command:
      - |
        CI=true npm start || (\
          echo "⛔ \`npm start\` failed, but the container is running..." && \
          tail -f /dev/null \
        )
    ports:
      - 3000:3000

  agent:
    image: node:14.8
    volumes:
      - "./agent:/mnt/agent"
    working_dir: "/mnt/agent"
    environment:
      TARGET_URL: "http://target:80"
      PORT: 7070
    entrypoint: "/bin/bash -c"
    command:
      - |
        npm run start:dev || (\
          echo "⛔ \`npm start\` failed, but the container is running..." && \
          tail -f /dev/null \
        )
    ports:
      - 7070:7070

  target:
    image: nginx
    # volumes:
    #  - ./templates:/etc/nginx/templates
    ports:
     - "8080:80"
    environment:
    #  - NGINX_HOST=foobar.com
     - NGINX_PORT=80
